apiVersion: v1
kind: Service
metadata:
  name: ratingsweb-service
  namespace: aks-workshop-dev
spec:
  selector:
    app: ratingsweb-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP